server:
   port: 8001

spring:
  application:
     name: ebuy-order
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/C76-S3-Wyx-ebuy
     username: root
     password: 123
     driver-class-name: com.mysql.jdbc.Driver

mybatis:
  #实体类的路径
  type-aliases-package: com.yc.ebuy.bean
  configuration:
     map-underscore-to-camel-case: true

# 日志配置
logging:
  level:
    com:
      yc:
        ebuy:
          dao: debug
          web: warn 